version: 0.0
os: linux
files:
  - source: /
    destination: /root/toolplate-backend
permissions:
  - object: /root/toolplate-backend
    pattern:
      - "**/*"
    owner: ec2-user
    group: ec2-user
    mode: 777

hooks:
  ApplicationStart:
    - location: script/update.sh
      timeout: 300
      runas: root
