version: 0.0
os: linux
files:
  - source: /
    destination: /root/toolplate-backend
file_exists_behavior: OVERWRITE
hooks:
  ApplicationStart:
    - location: script/update.sh
      timeout: 300
      runas: root
