const Joi = require("joi");

module.exports = {
  create: Joi.object().keys({
    title: Joi.string().required(),
    description: Joi.string().required(),
    image: Joi.string(),
    price: Joi.string().valid("Free", "Premium", "Freemium").required(),
    previews: Joi.array(),
    overview: Joi.string(),
    link: Joi.string().required(),
    videos: Joi.string().allow(null),
    categories: Joi.string().required(),
    release: Joi.date(),
    social: Joi.string(),
    isExtension: Joi.boolean(),
    isApi: Joi.boolean(),
    pros: Joi.string(),
    cons: Joi.string(),
  }),
  update: Joi.object().keys({
    title: Joi.string(),
    description: Joi.string(),
    // slug: Joi.string(),
    image: Joi.string(),
    price: Joi.string().valid("Free", "Premium", "Freemium"),
    overview: Joi.string(),
    link: Joi.string(),
    videos: Joi.string(),
    categories: Joi.string(),
    release: Joi.date(),
    social: Joi.string(),
    isExtension: Joi.boolean(),
    isApi: Joi.boolean(),
    pros: Joi.string(),
    cons: Joi.string(),
  }),
};
